import 'dotenv/config';
import express from 'express';
import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import { calculateRubKopeks, DEFAULT_USDT_RATE, parseRateKopeks, parseRubKopeks, parseUsdtMicro, USDT_MICRO } from './financial.js';

const env=process.env,app=express(),PORT=Number(env.PORT||3000);
const ADMIN_IDS=(env.ADMIN_TELEGRAM_IDS||env.ADMIN_TELEGRAM_ID||'').split(',').map(x=>x.trim()).filter(Boolean);
const RATE_KOPEKS=parseRateKopeks(env.USDT_RATE||DEFAULT_USDT_RATE),MICRO=USDT_MICRO;
const users=new Map(),deposits=new Map(),exchanges=new Map(),payouts=new Map(),transactions=new Map(),supports=new Map(),supportMessages=new Map(),pendingActions=new Map(),idempotency=new Map(),auditLog=[];
const n=x=>Number(x||0),usdt=x=>n(x)/MICRO,rub=x=>n(x)/100,isAdmin=id=>ADMIN_IDS.includes(String(id));
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
app.disable('x-powered-by');app.use(express.json({limit:'64kb'}));
app.use((req,res,next)=>{const origin=req.get('Origin'),allowed=(env.WEBAPP_ORIGINS||env.WEBAPP_ORIGIN||'https://hjibibu-bxqc.vercel.app').split(',').map(x=>x.trim());if(origin&&allowed.includes(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type,X-Telegram-Init-Data,X-Telegram-Bot-Api-Secret-Token,Idempotency-Key');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
function verifyInitData(raw){if(!raw||!env.TELEGRAM_BOT_TOKEN)throw fail('Telegram authentication is not configured',401);const p=new URLSearchParams(raw),hash=p.get('hash');if(!hash)throw fail('Telegram init data is invalid',401);p.delete('hash');const check=[...p.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n'),secret=createHmac('sha256','WebAppData').update(env.TELEGRAM_BOT_TOKEN).digest(),expected=createHmac('sha256',secret).update(check).digest('hex'),a=Buffer.from(hash,'hex'),b=Buffer.from(expected,'hex');if(a.length!==b.length||!timingSafeEqual(a,b))throw fail('Telegram authentication failed',401);if(Date.now()/1000-Number(p.get('auth_date'))>86400)throw fail('Telegram session expired',401);try{const u=JSON.parse(p.get('user')||'{}');if(!u.id)throw 0;return u}catch{throw fail('Telegram user is missing',401)}}
function getUser(id,telegramUser={}){const key=String(id);if(!users.has(key))users.set(key,{telegramId:key,username:null,firstName:'Пользователь',avatar:null,balanceMicro:0,reservedMicro:0,statistics:{transactionsCount:0,usdtTurnoverMicro:0,rubTurnoverKopeks:0},recipientPhone:'',recipientBank:'',recipientFullName:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const u=users.get(key);if(telegramUser.first_name)u.firstName=telegramUser.first_name;if(telegramUser.username)u.username=telegramUser.username;if(telegramUser.photo_url)u.avatar=telegramUser.photo_url;u.updatedAt=new Date().toISOString();return u}
function auth(req,res,next){try{const t=verifyInitData(req.get('X-Telegram-Init-Data'));req.user=getUser(t.id,t);next()}catch(e){next(e)}}
async function telegram(method,payload){if(!env.TELEGRAM_BOT_TOKEN)throw Error('TELEGRAM_BOT_TOKEN is not configured');const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.description||`Telegram ${method} failed`);return j}
async function notifyAdmins(method,payload){const outcomes=await Promise.allSettled(ADMIN_IDS.map(chat_id=>telegram(method,{...payload,chat_id})));outcomes.forEach((x,i)=>{if(x.status==='rejected')console.error(`Admin notification failed ${ADMIN_IDS[i]}: ${x.reason?.message}`)});return outcomes.some(x=>x.status==='fulfilled')}
function audit(admin,action,entity,metadata={}){auditLog.push({adminId:String(admin),action,entityId:String(entity),metadata,createdAt:new Date().toISOString()})}
function history(userId){return (transactions.get(String(userId))||[]).slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
function userDto(u){return {telegramId:Number(u.telegramId),username:u.username,firstName:u.firstName,avatar:u.avatar,recipientPhone:u.recipientPhone,recipientBank:u.recipientBank,recipientFullName:u.recipientFullName}}
function walletDto(u){return {balanceUSDT:usdt(u.balanceMicro),reservedUSDT:usdt(u.reservedMicro),availableUSDT:usdt(u.balanceMicro-u.reservedMicro)}}
function logTransaction(userId,row){const list=transactions.get(String(userId))||[];if(!list.some(x=>x.id===row.id))list.push(row);transactions.set(String(userId),list)}
async function configureWebhook(){const base=(env.RENDER_EXTERNAL_URL||'').replace(/\/$/,'');if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_WEBHOOK_SECRET||!base)return;try{await telegram('setWebhook',{url:`${base}/api/telegram/webhook`,secret_token:env.TELEGRAM_WEBHOOK_SECRET,allowed_updates:['message','callback_query'],drop_pending_updates:false})}catch(e){console.error('Webhook setup failed:',e.message)}}
app.get('/health',(_q,s)=>s.json({status:'ok',storage:'memory'}));
app.get('/ready',(_q,s)=>{const missing=[];if(!env.TELEGRAM_BOT_TOKEN)missing.push('TELEGRAM_BOT_TOKEN');if(!env.TELEGRAM_WEBHOOK_SECRET)missing.push('TELEGRAM_WEBHOOK_SECRET');if(!ADMIN_IDS.length)missing.push('ADMIN_TELEGRAM_IDS');s.status(missing.length?503:200).json({status:missing.length?'needs-config':'ready',missing,storage:'memory',warning:'Data resets when the service restarts.'})});
app.get('/api/me',auth,(req,res)=>{const u=req.user;res.json({user:userDto(u),wallet:walletDto(u),statistics:{transactionsCount:u.statistics.transactionsCount,usdtTurnover:usdt(u.statistics.usdtTurnoverMicro),rubTurnover:u.statistics.rubTurnoverKopeks/100},rate:RATE_KOPEKS/100,history:history(u.telegramId)})});
app.get('/api/history',auth,(req,res)=>res.json(history(req.user.telegramId)));
app.put('/api/profile/recipient-details',auth,(req,res,next)=>{try{const phone=String(req.body?.recipientPhone||'').trim(),bank=String(req.body?.recipientBank||'').trim(),name=String(req.body?.recipientFullName||'').trim();if(!/^\+?[0-9 ()-]{10,20}$/.test(phone)||phone.replace(/\D/g,'').length<10||bank.length<2||bank.length>80||name.length<5||name.length>120)throw fail('Укажите корректный телефон, банк и ФИО');Object.assign(req.user,{recipientPhone:phone,recipientBank:bank,recipientFullName:name,updatedAt:new Date().toISOString()});res.json({recipient:{recipientPhone:phone,recipientBank:bank,recipientFullName:name,updatedAt:req.user.updatedAt}})}catch(e){next(e)}});
app.post('/api/deposits',auth,async(req,res,next)=>{try{const check=typeof req.body?.cryptoBotCheck==='string'?req.body.cryptoBotCheck.trim():'';if(!check||check.length>2048)throw fail('Введите корректный чек CryptoBot');const d={id:randomUUID(),userId:req.user.telegramId,check,amountMicro:null,status:'PENDING',createdAt:new Date().toISOString()};deposits.set(d.id,d);const sent=ADMIN_IDS.length?await notifyAdmins('sendMessage',{text:`Новое пополнение #${d.id}\nПользователь: ${req.user.firstName} (@${req.user.username||'—'})\nTelegram ID: ${d.userId}\nЧек: ${check}\nСоздано: ${d.createdAt}`,reply_markup:{inline_keyboard:[[{text:'Подтвердить',callback_data:`dep:approve:${d.id}`},{text:'Отклонить',callback_data:`dep:reject:${d.id}`}]]}}):false;await telegram('sendMessage',{chat_id:d.userId,text:'Чек на пополнение отправлен на проверку. Баланс будет зачислен после подтверждения администратором.'}).catch(()=>{});res.status(201).json({id:d.id,status:d.status,createdAt:d.createdAt,notificationSent:sent})}catch(e){next(e)}});
app.post('/api/exchanges',auth,async(req,res,next)=>{try{const amountMicro=parseUsdtMicro(req.body?.amountUSDT);if(!amountMicro||amountMicro>1_000_000*MICRO)throw fail('Проверьте сумму');const key=req.get('Idempotency-Key')||req.body?.idempotencyKey||randomUUID();if(idempotency.has(key)){const old=exchanges.get(idempotency.get(key));return res.status(200).json({id:old.id,status:old.status,idempotent:true})}const u=req.user;if(!u.recipientPhone||!u.recipientBank||!u.recipientFullName)throw fail('Сначала укажите реквизиты в профиле');if(u.balanceMicro-u.reservedMicro<amountMicro)throw fail('Недостаточно доступных средств',409);if([...exchanges.values()].some(x=>x.userId===u.telegramId&&['WAITING_ADMIN','PROCESSING','PARTIALLY_PAID','MANAGER_CONTACT'].includes(x.status)))throw fail('У вас уже есть незавершённая заявка',409);const amountRubKopeks=calculateRubKopeks(amountMicro,RATE_KOPEKS);const x={id:randomUUID(),userId:u.telegramId,amountMicro,rateKopeks:RATE_KOPEKS,amountRubKopeks,paidRubKopeks:0,recipientPhone:u.recipientPhone,recipientBank:u.recipientBank,recipientFullName:u.recipientFullName,status:'WAITING_ADMIN',idempotencyKey:key,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};exchanges.set(x.id,x);idempotency.set(key,x.id);u.reservedMicro+=amountMicro;const sent=await notifyAdmins('sendMessage',{text:`Заявка на вывод #${x.id}\n${usdt(amountMicro)} USDT · ${RATE_KOPEKS/100} ₽/USDT\nК выплате: ${rub(amountRubKopeks).toLocaleString('ru-RU')} ₽\nПолучатель: ${x.recipientFullName}\nТелефон: ${x.recipientPhone}\nБанк: ${x.recipientBank}\nTelegram ID: ${x.userId}`,reply_markup:{inline_keyboard:[[{text:'Начать обработку',callback_data:`wd:start:${x.id}`},{text:'Связаться',callback_data:`wd:contact:${x.id}`}],[{text:'Отклонить',callback_data:`wd:reject:${x.id}`},{text:'Выплатить часть',callback_data:`wd:payout:${x.id}`}]]}});await telegram('sendMessage',{chat_id:x.userId,text:`Заявка на вывод принята. Сумма ${usdt(amountMicro)} USDT, ориентировочно ${rub(amountRubKopeks)} ₽. Ожидайте обработки.`}).catch(()=>{});res.status(201).json({id:x.id,status:x.status,botMessageSent:sent,wallet:walletDto(u)})}catch(e){next(e)}});
function completeExchange(x){if(x.status==='COMPLETED')return;const u=users.get(x.userId);if(!u)return;u.balanceMicro-=x.amountMicro;u.reservedMicro-=x.amountMicro;u.statistics.transactionsCount++;u.statistics.usdtTurnoverMicro+=x.amountMicro;u.statistics.rubTurnoverKopeks+=x.amountRubKopeks;x.status='COMPLETED';x.updatedAt=new Date().toISOString();logTransaction(u.telegramId,{id:x.id,type:'Обмен',amountUSDT:usdt(x.amountMicro),rate:x.rateKopeks/100,amountRUB:rub(x.amountRubKopeks),status:'COMPLETED',createdAt:x.updatedAt})}
function getOrCreateSupport(userId){let t=[...supports.values()].find(x=>x.userId===String(userId)&&x.status!=='CLOSED');if(t)return t;t={id:randomUUID(),userId:String(userId),adminId:null,status:'OPEN',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};supports.set(t.id,t);return t}
async function handleCallback(q){await telegram('answerCallbackQuery',{callback_query_id:q.id}).catch(()=>{});const [scope,action,id]=String(q.data||'').split(':');if(scope==='dep'){if(!isAdmin(q.from.id))return;const d=deposits.get(id);if(!d||d.status!=='PENDING')return telegram('sendMessage',{chat_id:q.from.id,text:'Заявка уже обработана или не найдена.'});if(action==='reject'){d.status='REJECTED';d.updatedAt=new Date().toISOString();audit(q.from.id,'deposit.rejected',id);await telegram('sendMessage',{chat_id:d.userId,text:'Заявка на пополнение отклонена. Если считаете это ошибкой, обратитесь к менеджеру.'}).catch(()=>{});return telegram('sendMessage',{chat_id:q.from.id,text:'Заявка отклонена.'})}if(action==='approve'){pendingActions.set(String(q.from.id),{action:'deposit_amount',entityId:id});return telegram('sendMessage',{chat_id:q.from.id,text:`Введите сумму USDT для пополнения #${id}`,reply_markup:{force_reply:true}})}}
if(scope==='wd'){if(!isAdmin(q.from.id))return;const x=exchanges.get(id);if(!x)return;if(action==='start'){if(x.status!=='WAITING_ADMIN')return; x.status='PROCESSING';x.updatedAt=new Date().toISOString();audit(q.from.id,'withdrawal.started',id);return telegram('sendMessage',{chat_id:x.userId,text:'Менеджер начал обработку вашей заявки. Мы сообщим, когда будет отправлен перевод.'})}if(action==='reject'){if(!['WAITING_ADMIN','PROCESSING'].includes(x.status)||[...payouts.values()].some(p=>p.requestId===id))return telegram('sendMessage',{chat_id:q.from.id,text:'Эту заявку нельзя отклонить после создания выплат.'});x.status='REJECTED';users.get(x.userId).reservedMicro-=x.amountMicro;x.updatedAt=new Date().toISOString();audit(q.from.id,'withdrawal.rejected',id);return telegram('sendMessage',{chat_id:x.userId,text:'Заявка на вывод отклонена, зарезервированные USDT снова доступны.'})}if(action==='payout'){if(!['PROCESSING','PARTIALLY_PAID'].includes(x.status))return telegram('sendMessage',{chat_id:q.from.id,text:'Сначала начните обработку заявки.'});pendingActions.set(String(q.from.id),{action:'payout_amount',entityId:id});return telegram('sendMessage',{chat_id:q.from.id,text:`Введите сумму частичной выплаты в рублях для заявки ${id}`,reply_markup:{force_reply:true}})}if(action==='contact'){if(x.status==='WAITING_ADMIN')x.status='PROCESSING';const t=getOrCreateSupport(x.userId);return telegram('sendMessage',{chat_id:x.userId,text:`Менеджер подключился к заявке. Напишите сюда, если нужно уточнить детали. Обращение ${t.id}`})}}
if(scope==='pay'){if(action==='adminyes'&&!isAdmin(q.from.id))return;const p=payouts.get(id),x=p&&exchanges.get(p.requestId);if(!p||!x||(!isAdmin(q.from.id)&&x.userId!==String(q.from.id)))return;if(action==='yes'||action==='adminyes'){if(p.status==='PAID')return telegram('sendMessage',{chat_id:q.from.id,text:'Эта выплата уже учтена.'});if(!['SENT','DISPUTED'].includes(p.status))return;p.status='PAID';p.userConfirmedAt=new Date().toISOString();p.updatedAt=p.userConfirmedAt;x.paidRubKopeks=[...payouts.values()].filter(z=>z.requestId===x.id&&z.status==='PAID').reduce((sum,z)=>sum+z.amountRubKopeks,0);if(x.paidRubKopeks>=x.amountRubKopeks){completeExchange(x);audit(q.from.id,'withdrawal.completed',x.id);await telegram('sendMessage',{chat_id:x.userId,text:`Все выплаты подтверждены, сделка завершена. Баланс: ${usdt(users.get(x.userId).balanceMicro)} USDT.`});return notifyAdmins('sendMessage',{text:`Заявка ${x.id} полностью выплачена.`})}x.status='PARTIALLY_PAID';return telegram('sendMessage',{chat_id:x.userId,text:'Поступление подтверждено. Ожидайте оставшуюся часть выплаты.'})}if(action==='no'){if(p.status!=='SENT')return; p.status='DISPUTED';p.updatedAt=new Date().toISOString();return telegram('sendMessage',{chat_id:x.userId,text:'Пришлите скриншот истории операций из банковского приложения, менеджер проверит перевод.'})}if(action==='manager')return telegram('sendMessage',{chat_id:x.userId,text:'Напишите сообщение сюда — оно будет передано менеджеру.'})}
if(scope==='support'){if(action==='start'){getOrCreateSupport(q.from.id);return telegram('sendMessage',{chat_id:q.from.id,text:'Напишите сообщение менеджеру. Можно отправить текст, скриншот или файл.'})}if(!isAdmin(q.from.id))return;const t=supports.get(id);if(!t)return;if(action==='close'){t.status='CLOSED';t.updatedAt=new Date().toISOString();audit(q.from.id,'support.closed',id);return telegram('sendMessage',{chat_id:t.userId,text:'Обращение закрыто. Если понадобится помощь, напишите нам снова.'})}if(action==='reply'){pendingActions.set(String(q.from.id),{action:'support_reply',entityId:id});return telegram('sendMessage',{chat_id:q.from.id,text:'Введите ответ пользователю:',reply_markup:{force_reply:true}})}}}
async function handleMessage(m){const uid=String(m.from.id),text=m.text||'';if(text.startsWith('/start')){if(isAdmin(uid))return telegram('sendMessage',{chat_id:m.chat.id,text:'TONIX Admin готов. Заявки доступны через уведомления.'});const u=getUser(uid,m.from);return telegram('sendMessage',{chat_id:m.chat.id,text:`Добро пожаловать в TONIX, ${u.firstName}!\nБаланс: ${usdt(u.balanceMicro)} USDT\nКурс: ${RATE_KOPEKS/100} ₽ за USDT`,reply_markup:{inline_keyboard:[[{text:'Открыть TONIX',web_app:{url:env.MINI_APP_URL||'https://hjibibu-bxqc.vercel.app'}}],[{text:'Связаться с менеджером',callback_data:'support:start'}]]}})}
if(isAdmin(uid)){const pending=pendingActions.get(uid);if(pending){if(pending.action==='deposit_amount'){const amount=parseUsdtMicro(text);if(!amount)return telegram('sendMessage',{chat_id:m.chat.id,text:'Введите положительную сумму USDT, до 6 знаков после запятой.'});const d=deposits.get(pending.entityId);if(!d||d.status!=='PENDING'){pendingActions.delete(uid);return telegram('sendMessage',{chat_id:m.chat.id,text:'Заявка уже обработана или не найдена.'})}const u=users.get(d.userId);d.amountMicro=amount;d.status='APPROVED';d.confirmedBy=uid;d.updatedAt=new Date().toISOString();u.balanceMicro+=amount;logTransaction(u.telegramId,{id:d.id,type:'Пополнение',amountUSDT:usdt(amount),rate:0,amountRUB:0,status:'APPROVED',createdAt:d.updatedAt});audit(uid,'deposit.approved',d.id,{amountMicro:amount});pendingActions.delete(uid);await telegram('sendMessage',{chat_id:u.telegramId,text:`Пополнение подтверждено. Зачислено ${usdt(amount)} USDT. Баланс: ${usdt(u.balanceMicro)} USDT.`}).catch(()=>{});return telegram('sendMessage',{chat_id:m.chat.id,text:`Заявка #${d.id} подтверждена.`})}
if(pending.action==='payout_amount'){const amountRubKopeks=parseRubKopeks(text);if(!amountRubKopeks)return telegram('sendMessage',{chat_id:m.chat.id,text:'Введите положительную сумму рублей, максимум 2 знака после запятой.'});const x=exchanges.get(pending.entityId);if(!x||!['PROCESSING','PARTIALLY_PAID'].includes(x.status)){pendingActions.delete(uid);return telegram('sendMessage',{chat_id:m.chat.id,text:'Заявка не найдена или закрыта.'})}const used=[...payouts.values()].filter(p=>p.requestId===x.id&&['SENT','PAID'].includes(p.status)).reduce((sum,p)=>sum+p.amountRubKopeks,0);if(amountRubKopeks>x.amountRubKopeks-used)return telegram('sendMessage',{chat_id:m.chat.id,text:'Сумма превышает остаток к выплате.'});const payoutNumber=[...payouts.values()].filter(p=>p.requestId===x.id).reduce((max,p)=>Math.max(max,p.payoutNumber),0)+1;const p={id:randomUUID(),requestId:x.id,payoutNumber,amountRubKopeks,adminId:uid,status:'SENT',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),userConfirmedAt:null,screenshotFileId:null};payouts.set(p.id,p);x.status='PARTIALLY_PAID';x.updatedAt=p.createdAt;pendingActions.delete(uid);audit(uid,'payout.created',p.id,{amountRubKopeks});await telegram('sendMessage',{chat_id:x.userId,text:`Менеджер отправил вам ${rub(amountRubKopeks).toLocaleString('ru-RU')} ₽ (часть ${p.payoutNumber}). Подтвердите поступление.`,reply_markup:{inline_keyboard:[[{text:'Деньги получил',callback_data:`pay:yes:${p.id}`}],[{text:'Не получил',callback_data:`pay:no:${p.id}`},{text:'Менеджер',callback_data:`pay:manager:${p.id}`}]]}});return telegram('sendMessage',{chat_id:m.chat.id,text:`Частичная выплата #${p.payoutNumber} создана.`})}
if(pending.action==='support_reply'){const t=supports.get(pending.entityId);pendingActions.delete(uid);if(!t)return telegram('sendMessage',{chat_id:m.chat.id,text:'Обращение не найдено.'});addSupportMessage(t.id,uid,'ADMIN','TEXT',text,null,m);t.status='WAITING_USER';t.adminId=uid;t.updatedAt=new Date().toISOString();await telegram('sendMessage',{chat_id:t.userId,text:`Сообщение менеджера:\n${text}`});return telegram('sendMessage',{chat_id:m.chat.id,text:'Ответ отправлен.'})}}
return telegram('sendMessage',{chat_id:m.chat.id,text:'У вас нет ожидающего действия.'})}
if(m.photo||m.document||m.video||m.voice){const disputed=[...payouts.values()].find(p=>p.status==='DISPUTED'&&exchanges.get(p.requestId)?.userId===uid&&!p.screenshotFileId);if(m.photo&&disputed){const x=exchanges.get(disputed.requestId),file=m.photo.at(-1).file_id;disputed.screenshotFileId=file;disputed.updatedAt=new Date().toISOString();await Promise.allSettled(ADMIN_IDS.map(chat_id=>telegram('sendPhoto',{chat_id,photo:file,caption:`Скриншот по выплате ${disputed.id}, заявка ${x.id}; пользователь ${uid}`,reply_markup:{inline_keyboard:[[{text:'Подтвердить выплату',callback_data:`pay:adminyes:${disputed.id}`}]]}})));return telegram('sendMessage',{chat_id:m.chat.id,text:'Скриншот передан администраторам.'})}const t=getOrCreateSupport(uid),media=m.photo?.at(-1)||m.document||m.video||m.voice,kind=m.photo?'PHOTO':m.document?'DOCUMENT':m.video?'VIDEO':'VOICE';addSupportMessage(t.id,uid,'USER',kind,m.caption||null,media?.file_id,m);const method=m.photo?'sendPhoto':m.document?'sendDocument':m.video?'sendVideo':'sendVoice',field=m.photo?'photo':m.document?'document':m.video?'video':'voice';await Promise.allSettled(ADMIN_IDS.map(chat_id=>telegram(method,{chat_id,[field]:media.file_id,caption:`Обращение ${t.id} · пользователь ${uid}${m.caption?`\n${m.caption}`:''}`,reply_markup:{inline_keyboard:[[{text:'Ответить',callback_data:`support:reply:${t.id}`},{text:'Закрыть',callback_data:`support:close:${t.id}`}]]}})));t.status='WAITING_ADMIN';t.updatedAt=new Date().toISOString();return telegram('sendMessage',{chat_id:m.chat.id,text:'Файл передан менеджеру.'})}
if(!text)return;const t=getOrCreateSupport(uid);addSupportMessage(t.id,uid,'USER','TEXT',text,null,m);t.status='WAITING_ADMIN';t.updatedAt=new Date().toISOString();await notifyAdmins('sendMessage',{text:`Сообщение поддержки · ${uid}\n${text}`,reply_markup:{inline_keyboard:[[{text:'Ответить',callback_data:`support:reply:${t.id}`},{text:'Закрыть',callback_data:`support:close:${t.id}`}]]}});return telegram('sendMessage',{chat_id:m.chat.id,text:'Сообщение передано менеджеру.'})}
function addSupportMessage(threadId,senderId,role,type,textBody,fileId,m){const key=`${m.chat.id}:${m.message_id}`;if(supportMessages.has(key))return;supportMessages.set(key,{threadId,senderId:String(senderId),senderRole:role,messageType:type,textBody,telegramFileId:fileId,telegramChatId:String(m.chat.id),telegramMessageId:m.message_id,createdAt:new Date().toISOString()})}
app.post('/api/telegram/webhook',async(req,res,next)=>{if(env.NODE_ENV==='production'&&!env.TELEGRAM_WEBHOOK_SECRET)return res.status(503).json({error:'TELEGRAM_WEBHOOK_SECRET is required'});if(env.TELEGRAM_WEBHOOK_SECRET&&req.get('X-Telegram-Bot-Api-Secret-Token')!==env.TELEGRAM_WEBHOOK_SECRET)return res.sendStatus(401);try{if(req.body?.callback_query)await handleCallback(req.body.callback_query);if(req.body?.message)await handleMessage(req.body.message);res.sendStatus(200)}catch(e){next(e)}});
app.use((e,req,res,_next)=>{const requestId=randomUUID();console.error(JSON.stringify({requestId,path:req.path,method:req.method,message:e.message}));res.status(e.status||500).json({error:e.status?e.message:'Внутренняя ошибка сервера',requestId})});
app.listen(PORT,'0.0.0.0',()=>{console.log(`TONIX API listening on ${PORT}; in-memory storage enabled`);void configureWebhook()});
